export const Products = [
  {
    id: 1,
    name: 'Wireless Bluetooth Headphones',
    brand: 'Sony',
    category: 'Electronics',
    price: 2999,
    offer: 25,
    rating: 4.5,
    reviews: 1820,
    stock: true,
    image: 'https://picsum.photos/300?1',
    details:
      'Noise cancelling wireless headphones with deep bass and 20 hours battery life.',
    delivery: 'Free Delivery',
    color: 'Black',
  },
  {
    id: 2,
    name: 'Smart Fitness Watch',
    brand: 'Noise',
    category: 'Wearables',
    price: 2499,
    offer: 30,
    rating: 4.2,
    reviews: 950,
    stock: true,
    image: 'https://picsum.photos/300?2',
    details:
      'Fitness tracking watch with heart rate monitor and sleep tracking.',
    delivery: 'Free Delivery',
    color: 'Blue',
  },
  {
    id: 3,
    name: 'Gaming RGB Mouse',
    brand: 'Logitech',
    category: 'Accessories',
    price: 899,
    offer: 20,
    rating: 4.4,
    reviews: 420,
    stock: true,
    image: 'https://picsum.photos/300?3',
    details: 'Ergonomic gaming mouse with RGB lighting and adjustable DPI.',
    delivery: 'Prime Delivery',
    color: 'Black',
  },
  {
    id: 4,
    name: 'Mechanical Keyboard',
    brand: 'Redragon',
    category: 'Accessories',
    price: 3499,
    offer: 35,
    rating: 4.6,
    reviews: 680,
    stock: true,
    image: 'https://picsum.photos/300?4',
    details: 'RGB mechanical keyboard with blue switches and durable design.',
    delivery: 'Free Delivery',
    color: 'Black',
  },
  {
    id: 5,
    name: 'Portable Bluetooth Speaker',
    brand: 'JBL',
    category: 'Audio',
    price: 1799,
    offer: 18,
    rating: 4.3,
    reviews: 720,
    stock: true,
    image: 'https://picsum.photos/300?5',
    details: 'Compact waterproof Bluetooth speaker with powerful bass.',
    delivery: 'Free Delivery',
    color: 'Red',
  },
  {
    id: 6,
    name: 'Laptop Cooling Pad',
    brand: 'Zebronics',
    category: 'Laptop Accessories',
    price: 699,
    offer: 40,
    rating: 4.1,
    reviews: 510,
    stock: true,
    image: 'https://picsum.photos/300?6',
    details: 'Cooling pad with dual fans and adjustable stand.',
    delivery: 'Free Delivery',
    color: 'Black',
  },
  {
    id: 7,
    name: 'USB-C Fast Charger',
    brand: 'Samsung',
    category: 'Mobile Accessories',
    price: 999,
    offer: 15,
    rating: 4.4,
    reviews: 900,
    stock: true,
    image: 'https://picsum.photos/300?7',
    details: '25W USB-C fast charger compatible with Android smartphones.',
    delivery: 'Prime Delivery',
    color: 'White',
  },
  {
    id: 8,
    name: 'Laptop Backpack',
    brand: 'Skybags',
    category: 'Bags',
    price: 1599,
    offer: 50,
    rating: 4.5,
    reviews: 1200,
    stock: true,
    image: 'https://picsum.photos/300?8',
    details: 'Water resistant backpack with laptop compartment.',
    delivery: 'Free Delivery',
    color: 'Gray',
  },
  {
    id: 9,
    name: 'Smart LED TV 43 Inch',
    brand: 'Samsung',
    category: 'Electronics',
    price: 32999,
    offer: 20,
    rating: 4.6,
    reviews: 2100,
    stock: true,
    image: 'https://picsum.photos/300?9',
    details:
      '4K Ultra HD smart TV with HDR support and built-in streaming apps.',
    delivery: 'Free Delivery',
    color: 'Black',
  },
  {
    id: 10,
    name: 'Wireless Earbuds',
    brand: 'Boat',
    category: 'Audio',
    price: 1999,
    offer: 35,
    rating: 4.3,
    reviews: 1750,
    stock: true,
    image: 'https://picsum.photos/300?10',
    details:
      'True wireless earbuds with touch control and 24 hour battery life.',
    delivery: 'Prime Delivery',
    color: 'Black',
  },
  {
    id: 11,
    name: 'Gaming Laptop Stand',
    brand: 'Cosmic Byte',
    category: 'Laptop Accessories',
    price: 1299,
    offer: 25,
    rating: 4.2,
    reviews: 300,
    stock: true,
    image: 'https://picsum.photos/300?11',
    details: 'Adjustable aluminum laptop stand for gaming and work.',
    delivery: 'Free Delivery',
    color: 'Silver',
  },
  {
    id: 12,
    name: 'Power Bank 20000mAh',
    brand: 'Mi',
    category: 'Mobile Accessories',
    price: 1799,
    offer: 30,
    rating: 4.4,
    reviews: 980,
    stock: true,
    image: 'https://picsum.photos/300?12',
    details: 'High capacity power bank with dual USB output.',
    delivery: 'Prime Delivery',
    color: 'Black',
  },
  {
    id: 13,
    name: 'Office Chair Ergonomic',
    brand: 'GreenSoul',
    category: 'Furniture',
    price: 8999,
    offer: 28,
    rating: 4.5,
    reviews: 760,
    stock: true,
    image: 'https://picsum.photos/300?13',
    details: 'Comfortable ergonomic chair with adjustable armrest.',
    delivery: 'Free Delivery',
    color: 'Black',
  },
  {
    id: 14,
    name: 'Smartphone Tripod Stand',
    brand: 'Digitek',
    category: 'Accessories',
    price: 799,
    offer: 22,
    rating: 4.1,
    reviews: 250,
    stock: true,
    image: 'https://picsum.photos/300?14',
    details: 'Flexible tripod stand for smartphones and cameras.',
    delivery: 'Free Delivery',
    color: 'Black',
  },
  {
    id: 15,
    name: 'External Hard Drive 1TB',
    brand: 'Seagate',
    category: 'Storage',
    price: 4299,
    offer: 15,
    rating: 4.6,
    reviews: 1120,
    stock: true,
    image: 'https://picsum.photos/300?15',
    details: 'Portable external hard drive with fast USB 3.0 transfer.',
    delivery: 'Prime Delivery',
    color: 'Black',
  },
  {
    id: 16,
    name: 'Digital Drawing Tablet',
    brand: 'Wacom',
    category: 'Electronics',
    price: 5999,
    offer: 20,
    rating: 4.7,
    reviews: 430,
    stock: true,
    image: 'https://picsum.photos/300?16',
    details: 'Drawing tablet for designers with pressure sensitivity.',
    delivery: 'Free Delivery',
    color: 'Black',
  },
  {
    id: 17,
    name: 'Noise Cancelling Earphones',
    brand: 'Sony',
    category: 'Audio',
    price: 2499,
    offer: 18,
    rating: 4.3,
    reviews: 670,
    stock: true,
    image: 'https://picsum.photos/300?17',
    details: 'In-ear wired earphones with active noise cancellation.',
    delivery: 'Prime Delivery',
    color: 'Black',
  },
  {
    id: 18,
    name: 'Smart Home Security Camera',
    brand: 'TP-Link',
    category: 'Smart Home',
    price: 3199,
    offer: 27,
    rating: 4.4,
    reviews: 540,
    stock: true,
    image: 'https://picsum.photos/300?18',
    details: 'WiFi security camera with night vision and motion detection.',
    delivery: 'Free Delivery',
    color: 'White',
  },
  {
    id: 19,
    name: 'Portable Mini Projector',
    brand: 'ViewSonic',
    category: 'Electronics',
    price: 7999,
    offer: 32,
    rating: 4.2,
    reviews: 310,
    stock: true,
    image: 'https://picsum.photos/300?19',
    details: 'Mini HD projector for home theater and presentations.',
    delivery: 'Prime Delivery',
    color: 'White',
  },
  {
    id: 20,
    name: 'Wireless Gaming Controller',
    brand: 'Xbox',
    category: 'Gaming',
    price: 5499,
    offer: 12,
    rating: 4.7,
    reviews: 890,
    stock: true,
    image: 'https://picsum.photos/300?20',
    details: 'Wireless controller compatible with PC and Xbox consoles.',
    delivery: 'Free Delivery',
    color: 'Black',
  },
];
